import streamlit as st
import pandas as pd
from PIL import Image, ImageDraw, ImageFont
import io
import datetime

# ==========================================
# 1. 画像生成用ヘルパー関数
# ==========================================
def create_sns_image(race_info, df_rank, df_sorted):
    width, height = 1200, 675
    # PillowのImage.newの引数を正しく指定
    img = Image.new('RGB', (width, height), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)

    # アップロードしたフォントファイルを指定
    font_path = "NotoSansJP-Regular.ttf" 
    
    try:
        f_title = ImageFont.truetype(font_path, 45)
        f_header = ImageFont.truetype(font_path, 28)
        f_body = ImageFont.truetype(font_path, 22)
        f_rank_big = ImageFont.truetype(font_path, 32)
    except:
        # 万が一読み込めなかった場合のバックアップ
        st.error(f"フォントファイル '{font_path}' が見つかりません。GitHubへのアップロードとファイル名を確認してください。")
        f_title = f_header = f_body = f_rank_big = ImageFont.load_default()

    # --- デザイン描画 ---
    # ヘッダー帯 (濃紺)
    draw.rectangle([0, 0, width, 100], fill=(20, 40, 80))
    title_text = f"【事前簡易予想】 {race_info['place']} {race_info['num']}R"
    draw.text((40, 25), title_text, font=f_title, fill=(255, 255, 255))
    # 日付を右上に
    draw.text((width - 300, 35), race_info['date'], font=f_header, fill=(255, 255, 255))

    # --- 艇番固定ランキング表の描画 ---
    y_start = 140
    x_start = 50
    col_w = 220 # 列幅
    row_h = 55  # 行高

    # 表のヘッダーラベル
    headers = ["艇番", "モーター", "当地勝率", "枠番勝率", "枠番ST"]
    for i, h in enumerate(headers):
        draw.rectangle([x_start + i*col_w, y_start, x_start + (i+1)*col_w, y_start + row_h], outline=(0,0,0), width=2)
        draw.text((x_start + i*col_w + 15, y_start + 12), h, font=f_header, fill=(0, 0, 0))

    # 各艇のデータ行
    items = ["🚀 モーター", "🏟️ 当地勝率", "📈 枠番勝率", "⏱️ 枠番スタート"]
    for i in range(6):
        boat_label = f"{i+1}号艇"
        curr_y = y_start + (i+1)*row_h
        
        # 1列目 (艇番固定)
        draw.rectangle([x_start, curr_y, x_start + col_w, curr_y + row_h], outline=(0,0,0))
        draw.text((x_start + 15, curr_y + 12), boat_label, font=f_body, fill=(0,0,0))
        
        # 2列目以降 (順位と評価)
        for j, col_name in enumerate(items):
            # df_rankから値を取得
            val_text = df_rank.loc[boat_label, col_name]
            cell_x = x_start + (j+1)*col_w
            
            # 1位を赤、2位を黄色でハイライト
            bg = None
            if "1位" in val_text:
                bg = (255, 204, 204) # 薄い赤
            elif "2位" in val_text:
                bg = (255, 255, 204) # 薄い黄
            
            if bg:
                draw.rectangle([cell_x + 2, curr_y + 2, cell_x + col_w - 2, curr_y + row_h - 2], fill=bg)
            
            # 枠線とテキスト
            draw.rectangle([cell_x, curr_y, cell_x + col_w, curr_y + row_h], outline=(0,0,0))
            draw.text((cell_x + 15, curr_y + 12), val_text, font=f_body, fill=(0,0,0))

    # --- 総合予想 ％ の表示 (下部) ---
    st_y = 560
    draw.text((x_start, st_y), "【総合評価ランキング】", font=f_header, fill=(20, 40, 80))
    
    # 上位3艇を表示
    for i in range(min(3, len(df_sorted))):
        row = df_sorted.iloc[i]
        medal = ["🥇", "🥈", "🥉"][i]
        result_text = f"{medal} {int(row['艇番'])}号艇 ({row['予想％']}%)"
        # 1位だけ赤文字
        text_color = (211, 47, 47) if i == 0 else (0, 0, 0)
        draw.text((x_start + i*380, st_y + 50), result_text, font=f_rank_big, fill=text_color)

    # フッター（クレジット）
    draw.text((width - 400, height - 35), "Generated by Boat-AI Prediction Tool", font=f_body, fill=(180,180,180))

    return img

# ==========================================
# 2. メインUIエリア
# ==========================================
# 画面レイアウトを広く使う
st.set_page_config(page_title="Boat Race SNS Generator", layout="wide")

# タイトル
st.title("🎯 ボートレース事前予想 ＆ SNS画像生成")

# --- A. サイドバー：レース情報入力 ---
with st.sidebar:
    st.header("📋 レース情報設定")
    r_date = st.date_input("レース日", datetime.date.today())
    r_place = st.selectbox("開催地", ["平和島", "江戸川", "多摩川", "浜名湖", "蒲郡", "常滑", "津", "三国", "びわこ", "住之江", "尼崎", "鳴門", "丸亀", "児島", "宮島", "徳山", "下関", "若松", "芦屋", "福岡", "佐賀", "唐津", "大村"])
    r_num = st.number_input("レース番号", 1, 12, 12)
    race_info = {"date": str(r_date), "place": r_place, "num": r_num}

# 評価記号の定義
def get_symbol(val):
    symbols = {6: "◎", 5: "○", 4: "▲", 3: "△", 2: "×", 1: "・", 0: "無"}
    return symbols.get(val, "無")

# --- B. メインエリア：入力フォーム ---
with st.form("input_form"):
    st.markdown("##### 🚤 各艇の評価をスライダーで入力 (0:無 〜 6:極)")
    
    # 重み付け（固定）
    WEIGHTS = {"モーター": 0.25, "当地勝率": 0.2, "枠番勝率": 0.3, "枠番スタート": 0.25}
    
    raw_data = []
    
    # 2列で入力スライダーを並べる
    cols_input = st.columns(2)
    for i in range(1, 7):
        with cols_input[(i-1)%2]:
            # 艇番のヘッダー（SyntaxError回避のためシンプルな記述）
            st.markdown(f'<div style="background:#f1f3f5; border-left:5px solid #2d3436; padding:5px 10px; border-radius:4px; margin-bottom:5px;"><b>{i}号艇</b></div>', unsafe_allow_html=True)
            
            # 各項目の7段階スライダー
            m = st.select_slider(f"🚀 モーター", options=range(7), value=0, format_func=get_symbol, key=f"m_{i}")
            t = st.select_slider(f"🏟️ 当地勝率", options=range(7), value=0, format_func=get_symbol, key=f"t_{i}")
            w = st.select_slider(f"📈 枠番勝率", options=range(7), value=0, format_func=get_symbol, key=f"w_{i}")
            s = st.select_slider(f"⏱️ 枠番スタート", options=range(7), value=0, format_func=get_symbol, key=f"s_{i}")
            
            # 加重スコア計算
            score = (
                m * WEIGHTS["モーター"]
                + t * WEIGHTS["当地勝率"]
                + w * WEIGHTS["枠番勝率"]
                + s * WEIGHTS["枠番スタート"]
            )
            
            raw_data.append({
                "艇番": i,
                "モーター": m,
                "当地勝率": t,
                "枠番勝率": w,
                "枠番スタート": s,
                "総合スコア": score
            })
            
    # 解析ボタン
    submitted = st.form_submit_button("📊 解析 ＆ SNS画像生成", use_container_width=True, type="primary")

# --- C. 解析結果表示エリア (解析ボタンが押されたら表示) ---
if submitted:
    df = pd.DataFrame(raw_data)
    
    # 全員のスコアが0の場合は警告
    if df["総合スコア"].sum() == 0:
        st.warning("⚠️ スライダーを動かして評価を入力してください。")
    else:
        # --- データ加工ロジック ---
        # 1. 艇番固定の順位表データを作成
        rank_dict = {"艇番": [f"{i}号艇" for i in range(1, 7)]}
        items_map = [
            ("🚀 モーター", "モーター"),
            ("🏟️ 当地勝率", "当地勝率"),
            ("📈 枠番勝率", "枠番勝率"),
            ("⏱️ 枠番スタート", "枠番スタート")
        ]
        
        for label, col in items_map:
            # 項目ごとに順位付け（同点時はイン優先）
            df[f'{col}_順位'] = df[col].rank(method='min', ascending=False)
            # 順位(評価) の文字列を作成
            rank_dict[label] = [
                f"{int(r)}位({get_symbol(int(v))})" 
                for r, v in zip(df[f'{col}_順位'], df[col])
            ]
        
        # Web表示用・画像用DF
        df_rank = pd.DataFrame(rank_dict).set_index("艇番")
        
        # 2. 総合ポイントの％正規化
        total_score = df["総合スコア"].sum()
        df["予想％"] = (df["総合スコア"] / total_score * 100).round(1)
        
        # ％の高い順に並び替え
        df_sorted = df.sort_values("予想％", ascending=False).reset_index(drop=True)
        
        # 合計が必ず100.0%になるよう端数調整（1位の艇に差分を足す）
        diff = 100.0 - df_sorted["予想％"].sum()
        df_sorted.loc[0, "予想％"] = round(df_sorted.loc[0, "予想％"] + diff, 1)

        # ----------------------------------
        # Web画面への表示処理 (ここが追加部分)
        # ----------------------------------
        st.divider()
        st.subheader("📋 解析結果（Web表示）")
        
        # --- 1. 項目別順位表（Web版・スタイル適用） ---
        st.markdown("##### 項目別順位一覧")
        
        # 1位を赤、2位を黄色にするスタイル関数
        def style_web_ranks(val):
            if "1位" in val:
                return 'background-color: #ffcccc; color: #cc0000; font-weight: bold;'
            elif "2位" in val:
                return 'background-color: #ffffcc; color: #888800; font-weight: bold;'
            return ''

        # Web用の表を表示
        st.table(df_rank.style.applymap(style_web_ranks))

        # --- 2. 総合予想％カード（Web版） ---
        st.markdown("##### 総合予想％（買い目検討）")
        res_cols = st.columns(3)
        
        # 上位3艇をカード表示
        for i in range(min(3, len(df_sorted))):
            row = df_sorted.iloc[i]
            rank = i + 1
            boat = int(row["艇番"])
            pct = float(row["予想％"])
            
            # 順位ごとのデザイン
            colors = {
                1: ("#fff1c1", "#f39c12", "🥇"), # 金
                2: ("#f8f9fa", "#bdc3c7", "🥈"), # 銀
                3: ("#ffede5", "#e67e22", "🥉")  # 銅
            }
            bg, brd, icon = colors.get(rank, ("#ffffff", "#dfe6e9", f"{rank}位"))
            
            with res_cols[i % 3]:
                st.markdown(f"""
                    <div style="background:{bg}; border:2px solid {brd}; border-radius:12px; padding:15px; text-align:center; box-shadow:0 2px 4px rgba(0,0,0,0.05); margin-bottom:10px;">
                        <div style="font-size:12px; color:#636e72;">{icon}</div>
                        <div style="font-size:26px; font-weight:bold; color:#2d3436;">{boat}<span style="font-size:14px;">号艇</span></div>
                        <div style="font-size:22px; font-weight:bold; color:#e74c3c;">{pct:.1f}%</div>
                    </div>
                """, unsafe_allow_html=True)

        # ----------------------------------
        # SNS用画像の生成・保存エリア
        # ----------------------------------
        st.divider()
        st.subheader("🖼️ SNS投稿用画像（ダウンロード）")
        
        # 画像生成関数を実行
        img = create_sns_image(race_info, df_rank, df_sorted)
        
        # 画面に画像をプレビュー表示
        st.image(img, use_container_width=True)

        # 保存（ダウンロード）ボタン
