import streamlit as st
import pandas as pd
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import io
import datetime
import os
import gspread
from google.oauth2.service_account import Credentials
import base64
import pathlib
import plotly.express as px

# ==========================================
# 1. 基本設定・認証
# ==========================================
BASE_DIR = pathlib.Path(__file__).parent.resolve()
PLACE_NAME = "桐生" # 会場名
st.set_page_config(page_title=f"競艇Pro Pro Analytica - {PLACE_NAME}", layout="wide", page_icon="🎯")

# カスタムCSSでデザイン調整
st.markdown("""
    <style>
    .stApp { background-color: #f4f7f6; }
    .stSlider > label { font-weight: bold; color: #2c3e50; }
    .stButton > button { border-radius: 8px; font-weight: bold; transition: all 0.3s; }
    .stButton > button:hover { transform: translateY(-2px); box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    [data-testid="stMetricValue"] { font-size: 24px; color: #e74c3c; }
    </style>
""", unsafe_allow_html=True)

# Google Sheets 認証
scopes = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
try:
    creds = Credentials.from_service_account_info(st.secrets["gcp_service_account"], scopes=scopes)
    gc = gspread.authorize(creds)
except Exception as e:
    st.error(f"⚠️ Google Sheets接続エラー。Secretsの設定を確認してください。: {e}")
    st.stop()

# ==========================================
# 2. デザイン刷新版・画像生成関数 (SNS用)
# ==========================================
def create_modern_sns_image(race_info, df_sorted):
    # Twitter/X推奨比率 (16:9)
    width, height = 1280, 720
    img = Image.new('RGB', (width, height), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)
    
    # フォント読み込み
    font_path = "NotoSansJP-VariableFont_wght.ttf" 
    try:
        f_title = ImageFont.truetype("NotoSansJP-Bold.ttf", 60) # タイトルは太字
        f_header = ImageFont.truetype(font_path, 36)
        f_pct = ImageFont.truetype("NotoSansJP-Bold.ttf", 80)
        f_boat = ImageFont.truetype("NotoSansJP-Bold.ttf", 120)
        f_label = ImageFont.truetype(font_path, 24)
    except:
        f_title = f_header = f_pct = f_boat = f_label = ImageFont.load_default()

    # --- 背景デザイン ---
    # 上部ヘッダー（濃紺 gradient風）
    for y in range(120):
        color = (20 + y//4, 40 + y//3, 80 + y//2)
        draw.line([(0, y), (width, y)], fill=color)
        
    # タイトル
    title_text = f"🎯 {race_info['place']} {race_info['num']}R 事前予想"
    draw.text((40, 30), title_text, font=f_title, fill=(255, 255, 255))
    draw.text((width - 320, 50), race_info['date'], font=f_header, fill=(200, 200, 200))

    # --- 上位3艇のカードデザイン ---
    card_width = 380
    card_height = 480
    start_x = 60
    y_place = 160
    
    # 艇ごとのカラー定義（1-6号艇）
    boat_colors = {
        1: (230, 126, 34), # 橙
        2: (52, 152, 219),  # 青
        3: (231, 76, 60),   # 赤
        4: (241, 196, 15),  # 黄
        5: (46, 204, 113),  # 緑
        6: (149, 165, 166)  # 灰
    }

    for i in range(3):
        row = df_sorted.iloc[i]
        boat_no = int(row['艇番'])
        pct = float(row['予想％'])
        curr_x = start_x + (card_width + 30) * i
        
        # カード背景と枠線
        draw.rounded_rectangle([curr_x, y_place, curr_x + card_width, y_place + card_height], radius=20, fill=(250, 250, 250), outline=(200,200,200), width=2)
        
        # 順位ラベル
        rank_text = ["🥇 1番手", "🥈 2番手", "🥉 3番手"][i]
        draw.text((curr_x + 20, y_place + 20), rank_text, font=f_header, fill=(50, 50, 50))
        
        # 艇番（大きく）
        boat_txt = f"{boat_no}"
        draw.text((curr_x + card_width//2 - 40, y_place + 100), boat_txt, font=f_boat, fill=boat_colors.get(boat_no, (0,0,0)))
        draw.text((curr_x + card_width//2 + 50, y_place + 180), "号艇", font=f_header, fill=(100, 100, 100))

        # 予想％（強調）
        pct_txt = f"{pct:.1f}%"
        tw = draw.textlength(pct_txt, font=f_pct)
        draw.text((curr_x + card_width//2 - tw//2, y_place + 300), pct_txt, font=f_pct, fill=(211, 47, 47))

    # フッター
    draw.text((width - 450, height - 40), "Generated by Boat-AI Pro Analytica", font=f_label, fill=(180,180,180))

    return img

# ==========================================
# 3. メインUIエリア
# ==========================================
st.title(f"📊 {PLACE_NAME} Pro Analytica")
st.markdown(f"**Google Sheets 過去データ連動 & 統計解析システム**")

# --- A. データ管理パネル ---
with st.sidebar:
    st.header("📋 データ設定")
    r_date = st.date_input("レース日", datetime.date.today())
    # 開催地を選択可能に
    r_place = st.selectbox("開催地", ["桐生", "戸田", "江戸川", "多摩川", "平和島", "下関", "福岡"], index=0)
    r_num = st.number_input("レース番号", 1, 12, 12)
    
    st.divider()
    race_type_val = st.radio("解析データ対象", ["混合", "女子"], horizontal=True)
    target_sheet = f"{r_place}_{race_type_val}統計"
    
   if st.button("📈 過去データから最適重みを抽出", use_container_width=True):
                with st.spinner("統計解析中..."):
                    # 1. 必要な列だけを抽出
                    target_cols = ["展示", "直線", "回り足", "一周", "ST"]
                    # コピーを作成して、元のデータを壊さないようにする
                    work_df = df_base[target_cols + ["着順"]].copy()
                    
                    # 2. 強制的に数値に変換（文字や空欄は NaN になる）
                    for col in work_df.columns:
                        work_df[col] = pd.to_numeric(work_df[col], errors='coerce')
                    
                    # 3. NaN（数値でない行）をすべて削除
                    clean_df = work_df.dropna()
                    
                    # デバッグ用：有効なデータ数を表示（これで原因がわかります）
                    st.write(f"🔍 全 {len(df_base)} 行中、有効な数値データは {len(clean_df)} 行です")

                    if len(clean_df) < 10:
                        st.warning("⚠️ 数値として読み込めるデータが不足しています。シートの「着順」や各タイムが全角になっていないか、文字が入っていないか確認してください。")
                        st.session_state["auto_weights"] = {k: 0.2 for k in target_cols}
                    else:
                        # 4. 相関係数の計算
                        # 着順(1-6)とタイムは「正の相関」があるはず（タイムが遅い[大]ほど着順も悪い[大]）
                        corrs = {col: max(0.01, clean_df[col].corr(clean_df["着順"])) for col in target_cols}
                        total = sum(corrs.values())
                        st.session_state["auto_weights"] = {k: v/total for k, v in corrs.items()}
                        st.toast("統計重みの算出が完了しました！")
    if "base_df" in st.session_state:
        st.success(f"適用中: {target_sheet} ({len(st.session_state['base_df'])}件)")

st.divider()

# ==========================================
# 4. タブエリア（統合・刷新）
# ==========================================
tab_analytica, tab_sns = st.tabs(["🔍 統計解析 & 当日予想", "🖼️ SNS画像生成"])

Script execution error
File "/mount/src/s.tool/app.py", line 134
     if st.button("📈 過去データから最適重みを抽出", use_container_width=True):
                                                                ^
IndentationError: unindent does not match any outer indentation level
# --- タブ2：SNS画像生成 ---
with tab_sns:
    st.subheader("🖼️ SNS投稿用画像の生成・ダウンロード")
    
    if "analytica_result" in st.session_state:
        df_sorted = st.session_state["analytica_result"]
        race_info = {"place": r_place, "num": r_num, "date": str(r_date)}
        
        if st.button("✨ モダンデザイン画像を生成", use_container_width=True):
            with st.spinner("画像生成中..."):
                img = create_modern_sns_image(race_info, df_sorted)
                st.image(img, use_container_width=True, caption="生成された画像のプレビュー")
                
                # ダウンロードボタン
                buf = io.BytesIO()
                img.save(buf, format="PNG")
                st.download_button(
                    label="💾 この画像を保存する (PNG)",
                    data=buf.getvalue(),
                    file_name=f"yoso_{r_place}_{r_num}R.png",
                    mime="image/png",
                    use_container_width=True
                )
    else:
        st.info("「統計解析 & 当日予想」タブで予想を確定させてから、このタブを開いてください。")









